### ISSUE TITLE
ssh login for RGB-Pi OS?

### ISSUE THREAD

**Issue by squidrpi** [mortaca/RGB-Pi#48]
What's the username/password for ssh login? I don't see it documented anywhere.

**Comment by mortaca** [comment]
Is explained on the Information section inside the OS, are pi:rgbpi

**Comment by johnszewczyk** [comment]
Thanks, but what is the su / root password also?

**Comment by 03stevensmi** [comment]
> Thanks, but what is the su / root password also?

@mortaca ^^^ Are you taking the piss?

**Comment by BOGOmargaritas** [comment]
Any chance the root pass has been given?

**Comment by johnszewczyk** [comment]
No but all you need to do is put the SD card into a computer and manually set your sudoer file to add privileges Sent from my iPhoneOn Feb 26, 2025, at 16:23, Justin Bell ***@***.***> wrote:﻿
  Any chance the root pass has been given?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>



BOGOmargaritas left a comment (mortaca/RGB-Pi#48)
Any chance the root pass has been given?
