### ISSUE TITLE
AdvanceMame Core Support

### ISSUE THREAD

**Issue by mdd45** [mortaca/RGB-Pi#8]
add/fix AdvanceMame Core

**Comment by mortaca** [comment]
We are working on it, I hope for the next update to have it ready.

**Comment by mdd45** [comment]
Great!!!

**Comment by Sir-Ironic** [comment]
Advmame works very great on RGB-Pi.
Better than Mame2003 and FBA because the input lag is very very tiny.
scanlines (pixels perfect) and frequency are accurate
The only thing we must do is the ability to easily  setup input for paddles.
I must get parameters from EmulationStation inputs

I working on.
it's coming soon.

**Comment by mortaca** [comment]
Hi, AdvMAME is now included on the release.

**Comment by mdd45** [comment]
Great!!!!
